version: '3'
services:
  web:
    image: gufalcon/nexus-server-gui:latest
    restart: always
    ports:
      - "1380:80"
      - "13443:443"
    environment:
      - HTTP_PORT=80
      - HTTP_HOST=0.0.0.0
    volumes:
      - "/app/deploy/nexus-server-gui/nginx.conf:/etc/nginx/nginx.conf"
    command: ['nginx', '-g', 'daemon off;']
    labels:
       - "traefik.enable=true"
       - "traefik.nexus.port=80"
       - "traefik.nexus.backend=nexus"
       - "traefik.nexus.frontend.rule=Host:nexus.unterrainer.info"
       - "traefik.nexus.frontend.entryPoints=http,https"

networks:
  default:
    external:
      name: proxy_default